# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.eventmessage_create import EventmessageCreate  # noqa: E501

class TestEventmessageCreate(unittest.TestCase):
    """EventmessageCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventmessageCreate:
        """Test EventmessageCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventmessageCreate`
        """
        model = EventmessageCreate()  # noqa: E501
        if include_optional:
            return EventmessageCreate(
                id = 123456,
                timestamp = 1234123413,
                group = 1,
                group_id = 12345,
                msg_type = 1,
                src_did = 'did:sov:test:2234',
                des_did = 'did:sov:test:1234',
                msg = {optinal=values}
            )
        else:
            return EventmessageCreate(
                id = 123456,
                timestamp = 1234123413,
                group = 1,
                group_id = 12345,
                msg_type = 1,
                src_did = 'did:sov:test:2234',
                des_did = 'did:sov:test:1234',
                msg = {optinal=values},
        )
        """

    def testEventmessageCreate(self):
        """Test EventmessageCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
