# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_api import ServicesApi  # noqa: E501


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_service(self) -> None:
        """Test case for create_service

        Create Service  # noqa: E501
        """
        pass

    def test_delete_service(self) -> None:
        """Test case for delete_service

        Delete Service  # noqa: E501
        """
        pass

    def test_get_all_services(self) -> None:
        """Test case for get_all_services

        Get All Services  # noqa: E501
        """
        pass

    def test_get_service_by_did(self) -> None:
        """Test case for get_service_by_did

        Get Service By Did  # noqa: E501
        """
        pass

    def test_get_services_without_entity(self) -> None:
        """Test case for get_services_without_entity

        Get Services Without Entity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
