# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.repositories_api import RepositoriesApi  # noqa: E501


class TestRepositoriesApi(unittest.TestCase):
    """RepositoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RepositoriesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_all_repositories(self) -> None:
        """Test case for get_all_repositories

        Get All Repositories  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
