# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get(self) -> None:
        """Test case for get

        Get  # noqa: E501
        """
        pass

    def test_health(self) -> None:
        """Test case for health

        Health  # noqa: E501
        """
        pass

    def test_root(self) -> None:
        """Test case for root

        Root  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
