# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.clients_api import ClientsApi  # noqa: E501


class TestClientsApi(unittest.TestCase):
    """ClientsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClientsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_clients_by_did(self) -> None:
        """Test case for get_clients_by_did

        Get Clients By Did  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
