# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.resolution_api import ResolutionApi  # noqa: E501


class TestResolutionApi(unittest.TestCase):
    """ResolutionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResolutionApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_all_resolutions(self) -> None:
        """Test case for get_all_resolutions

        Get All Resolutions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
