# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.eventmessages_api import EventmessagesApi  # noqa: E501


class TestEventmessagesApi(unittest.TestCase):
    """EventmessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventmessagesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_eventmessage(self) -> None:
        """Test case for create_eventmessage

        Create Eventmessage  # noqa: E501
        """
        pass

    def test_get_all_eventmessages(self) -> None:
        """Test case for get_all_eventmessages

        Get All Eventmessages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
