# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.entities_api import EntitiesApi  # noqa: E501


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EntitiesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_attach_entity(self) -> None:
        """Test case for attach_entity

        Attach Entity  # noqa: E501
        """
        pass

    def test_create_entity(self) -> None:
        """Test case for create_entity

        Create Entity  # noqa: E501
        """
        pass

    def test_delete_entity(self) -> None:
        """Test case for delete_entity

        Delete Entity  # noqa: E501
        """
        pass

    def test_detach_entity(self) -> None:
        """Test case for detach_entity

        Detach Entity  # noqa: E501
        """
        pass

    def test_get_all_entities(self) -> None:
        """Test case for get_all_entities

        Get All Entities  # noqa: E501
        """
        pass

    def test_get_attached_entities(self) -> None:
        """Test case for get_attached_entities

        Get Attached Entities  # noqa: E501
        """
        pass

    def test_get_entity_by_did(self) -> None:
        """Test case for get_entity_by_did

        Get Entity By Did  # noqa: E501
        """
        pass

    def test_get_entity_by_name(self) -> None:
        """Test case for get_entity_by_name

        Get Entity By Name  # noqa: E501
        """
        pass

    def test_is_attached(self) -> None:
        """Test case for is_attached

        Is Attached  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
