name: checks
on:
  pull_request:
  push:
    branches: main
jobs:
  test:
    if: ${{ github.actor != 'ui-asset-bot' }}
    runs-on: nix
    steps:
      - uses: actions/checkout@v3
      - run: nix run --refresh github:Mic92/nix-fast-build -- --no-nom --eval-workers 8
