# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class Resolution(BaseModel):
    """
    Resolution
    """
    requester_name: Optional[StrictStr] = 'C1'
    requester_did: Optional[StrictStr] = 'did:sov:test:1122'
    resolved_did: Optional[StrictStr] = 'did:sov:test:1234'
    other: Optional[Dict[str, Any]] = None
    timestamp: datetime = Field(...)
    id: StrictInt = Field(...)
    __properties = ["requester_name", "requester_did", "resolved_did", "other", "timestamp", "id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Resolution:
        """Create an instance of Resolution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Resolution:
        """Create an instance of Resolution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Resolution.parse_obj(obj)

        _obj = Resolution.parse_obj({
            "requester_name": obj.get("requester_name") if obj.get("requester_name") is not None else 'C1',
            "requester_did": obj.get("requester_did") if obj.get("requester_did") is not None else 'did:sov:test:1122',
            "resolved_did": obj.get("resolved_did") if obj.get("resolved_did") is not None else 'did:sov:test:1234',
            "other": obj.get("other"),
            "timestamp": obj.get("timestamp"),
            "id": obj.get("id")
        })
        return _obj


